# Site-wide Settings

title: Men in Drag
tagline: Female a cappella like you've never heard it before
description: "Men in Drag is a female a cappella group from the University of Chicago"
baseurl: "" # subpath of your site e.g. /blog/, like if using github project page. Don't change unless you know what you're doing
locale: en_US
url: ""
repo: https://github.com/chloeam/men-in-drag
#google_analytics: UA-whatever


# Jekyll Configuration

markdown: kramdown
permalink: /:title/
gems: 
  - bourbon
  - neat

sass:
  sass_dir: assets/stylesheets


# Site Owner. Comment out what doesn't apply to you or you don't want to link to

group:
  name: Men in Drag
  email: mid@menindrag.org
  phone: "773-236-1MID (1643)"
  twitter: ucmenindrag
  facebook: ucmenindrag
  youtube: midacappella
  google_plus: your-gplus
  instagram: your-instagram
  disqus: chloeam
  picture: /assets/images/chloe.jpg # path to your picture. Remove if you don't want to show your picture.

positions:
  president: Kat Bovbjerg
  music_director: Frances Bernstein